### PR TITLE
Bump byteorder version to 1.x

### PR DESCRIPTION
**Pull request by messense**

### CODE REVIEW

**Comment by messense** [comment]
Is it OK to bump minimum rustc version?

**Comment by Nemo157** [comment]
If you're happy with fixing all the warnings then I'll accept updating the minimum version to the latest (in that case you can use the latest stable version to run clippy instead of running it on nightly). Otherwise you can get rid of the later commits, I'll just override CI to merge the version bump and sort out the nightly build later.

**Comment by messense** [comment]
I'd like to fix all the warnings.

**Comment by messense** [comment]
All warnings are fixed, bumped minimum rustc version to 1.17.0

**Comment by messense** [comment]
Ping.

**Comment by Nemo157** [comment]
Sorry I forgot about this. Thanks for doing it, I'll try and release a new version with this soon.

**Pull request merged**
