### PR TITLE
Bug fix for serialization bug

### PR DESCRIPTION
**Pull request by lemire**
See https://github.com/Nemo157/roaring-rs/pull/61

### CODE REVIEW

**Comment by Kerollmops** [comment]
The CI complains about my commit!

If you can just `cargo fmt` it could make the CI to pass :)

**Comment by lemire** [comment]
Ok. Did so.

**Comment by Nemo157** [comment]
Nice, thanks for the quick debugging. I should probably make sure there are boundary tests everywhere...

bors r+

**Comment by Kerollmops** [comment]
Hey @Nemo157 do you plan to make a new release soon, or do you want to add more tests first, like you said?

**Comment by Nemo157** [comment]
I'll publish a new version when I'm home tonight, we'll see if I get round to adding tests beforehand or not :grin:

**Comment by Nemo157** [comment]
:tada: 0.6.1 published

**Pull request merged**
